import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import { HomeServices } from '../services/index';
import { useEffect } from 'react';
import { HeaderComponent } from '@/components/Shared/Header/Header';
import { CustomizedTables } from '@/components/Home/Table';

const inter = Inter({ subsets: ['latin'] })
// utilizamos useEffect



export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HeaderComponent />
        <CustomizedTables></CustomizedTables>
      </div>
    </>
  )
}
